name: .NET Core xUnit Parallel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Укажите здесь пути к вашим файлам решений
        solution: [ './practice2026/practice2026/practice2026.slnx', './practice2026_2/practice2026_2/practice2026_2.slnx' ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.solution }}

    - name: Build
      run: dotnet build ${{ matrix.solution }} --no-restore

    - name: Test
      run: dotnet test ${{ matrix.solution }} --no-build --verbosity normal

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
